### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by FPS-86** [xN-o-vA/-ESX-Vehicles-Rent#1]
Привет у меня при запуске сервера выскакивает такое сообщение/Hi I have a message that POPs up when I start the server:

`[es_extended] [WARNING] Server callback "esx_truckshop:getVehicles" does not exist. Make sure that the server sided file really is loading, an error in that file might cause it to not load.
[es_extended] [WARNING] Server callback "esx_tvehicleshop:getVehicles" does not exist. Make sure that the server sided file really is loading, an error in that file might cause it to not load.`

Это нужно еще что то подключать дополнительные ресурсы?/This is something else you need to connect additional resources?

**Comment by xN-o-vA** [comment]
Привет , нет не чего подключать не нужно, забыл вырезать 1 вещь , вам нужно
вырезать --ESX.TriggerServerCallback('esx_truckshop:getVehicles', function
(vehicles)
    Vehicles = vehicles
  end)
это строчки 29,30,31 чуть позже исправлю это на github


вс, 23 февр. 2020 г. в 10:24, Irkutsk86 <notifications@github.com>:

**Comment by FPS-86** [comment]
Спасибо
