### ISSUE TITLE
SCRIPT ERROR: @esx_vehiclesRent/server/main.lua:41: attempt to compare number with nil

### ISSUE THREAD

**Issue by Achim-Sommer** [xN-o-vA/-ESX-Vehicles-Rent#4]
SCRIPT ERROR: @esx_vehiclesRent/server/main.lua:41: attempt to compare number with nil
> TriggerServerCallback (@es_extended/server/functions.lua:160)
> handler (@es_extended/server/common.lua:71)

instance version 1.1.0
es_extended version 1.2

How i can fix this

**Comment by bakerzone** [comment]
You could try this line GermanGaming:

if vehicle.price <= xPlayer.getAccount('bank').money then ----- LINE 41 Replace

As money is no longer a column name, I've not tested it though.
